web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development 
   MONGO_URL: mongodb://cmb:portfolio2019@ds117759.mlab.com:17759/cmb-studio
db:
  image: mongo:latest
  volumes:
   - ~/data/mongo:/data/db # "~/data/mongo" needs to be created on host to store MongoDB data
  ports:
   - "27017:27017"

